# Generated by Django 6.0.3 on 2026-03-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lote', models.DateField(auto_now_add=True)),
                ('Codigo_lote', models.CharField(max_length=20, unique=True)),
                ('trabador_encargado', models.CharField(max_length=100)),
                ('cantidad_producida', models.IntegerField()),
                ('Tamano_lote', models.IntegerField()),
            ],
        ),
    ]
