# Generated by Django 6.0.3 on 2026-03-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='Codigo_lote',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='Tamano_lote',
        ),
        migrations.AddField(
            model_name='lote',
            name='codigo_lote',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
