# Generated by Django 6.0.3 on 2026-03-19 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLote', '0002_remove_lote_codigo_lote_remove_lote_tamano_lote_and_more'),
        ('appTrabajador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='trabador_encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appTrabajador.trabajador'),
        ),
    ]
