# Generated by Django 6.0.3 on 2026-03-16 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCliente', '0001_initial'),
        ('appConductor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidones_retirados', models.IntegerField()),
                ('bidones_vacios', models.IntegerField()),
                ('fecha_hora_carrada', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCliente.cliente')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appConductor.conductor')),
            ],
        ),
    ]
