# Generated by Django 6.0.3 on 2026-03-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCarrada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrada',
            name='cliente',
        ),
    ]
