# Generated by Django 6.0.3 on 2026-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCarrada', '0002_remove_carrada_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrada',
            name='codigo_carrada',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='carrada',
            name='bidones_vacios',
            field=models.IntegerField(default=0),
        ),
    ]
