# Generated by Django 6.0.3 on 2026-03-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCarrada', '0003_carrada_codigo_carrada_alter_carrada_bidones_vacios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrada',
            name='codigo_carrada',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
