# Generated by Django 6.0.3 on 2026-03-19 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCarrada', '0004_alter_carrada_codigo_carrada'),
        ('appLote', '0003_alter_lote_trabador_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrada',
            name='lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appLote.lote'),
        ),
    ]
