# Generated by Django 6.0.3 on 2026-03-19 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLote', '0003_alter_lote_trabador_encargado'),
        ('appVenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appLote.lote'),
        ),
    ]
